#!/usr/bin/env bash
# Bu skript sonsuz döngüdə çap edir və SIGTERM siqnalını nəzərə almır.

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
